name: MasterDeployCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Deploy to GH Pages
      run: |
        git config --global user.email "kevin.haynes.dev@gmail.com"
        git config --global user.name "EsTOEban"
        git remote set-url origin https://95ac29f35afbe4411702cadef3fc9a59f63ebfbf@github.com/EsTOEban/personal-react-site.git
        npm run deploy
